Numpy: Numerical Python. most commonly used. supports large matrices and multi-dim data/table. consist of in-built mathematical functions. 

In [1]:
import numpy as np

In [2]:
#conda install numpy 

# Numpy Arrays

In [3]:
#Vectors: 1-d arrays
lst = [1,2,3]
lst

[1, 2, 3]

In [4]:
np.array(lst) #dimenson:1*3

array([1, 2, 3])

In [5]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built-in Methods

In [7]:
# arange

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [9]:
#zeros

np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#ones

np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Linspace

In [16]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [17]:
#eye

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random


### rand (random numbers uniformly distributed from 0 to 1)

In [19]:
np.random.rand(50)

array([8.12808717e-01, 2.92780669e-01, 4.07768800e-01, 9.70428405e-01,
       4.84050132e-01, 9.39189684e-01, 2.61419091e-01, 7.16466220e-01,
       8.31517428e-01, 9.74995177e-01, 1.03082440e-01, 5.32975873e-01,
       8.30760743e-01, 8.81042271e-01, 3.32896901e-01, 1.58865089e-01,
       8.35346663e-01, 2.61618666e-01, 5.47041592e-01, 2.57293178e-01,
       1.47992964e-01, 6.23087020e-01, 2.55891458e-02, 6.01865481e-01,
       9.71727103e-01, 6.34191547e-01, 2.84020235e-01, 9.74023342e-01,
       7.14709738e-01, 9.21155235e-01, 1.29124705e-01, 7.70742055e-01,
       9.47693575e-01, 5.60977153e-02, 2.23836717e-01, 4.11609420e-02,
       3.32112515e-04, 5.29704903e-01, 4.18015849e-01, 3.16109630e-01,
       6.54635746e-01, 6.21681547e-01, 2.12241645e-01, 5.92074841e-01,
       8.79016961e-01, 9.29112848e-01, 4.30086585e-01, 7.69464582e-01,
       4.59031899e-01, 5.47707031e-01])

In [22]:
np.random.rand(5,5)

array([[0.50893293, 0.39582813, 0.37359933, 0.14222768, 0.1302983 ],
       [0.21430831, 0.5076854 , 0.87753132, 0.35254318, 0.63753461],
       [0.98931334, 0.54119258, 0.11631286, 0.95140026, 0.55933748],
       [0.57033757, 0.30819988, 0.58230532, 0.04621146, 0.93783753],
       [0.07559215, 0.61359461, 0.91625129, 0.89870782, 0.73971327]])

In [23]:
#for standard normal distribution centered around zero

np.random.randn(5,5)

array([[ 1.35535162, -1.13742126,  1.11555768,  0.3463474 , -0.34004734],
       [ 1.54592693,  0.45188052,  0.93921746, -0.69604442,  0.33692119],
       [-0.35627136, -1.3883139 , -0.59317594, -0.16309782,  2.51109074],
       [ 0.63170129, -0.64653951,  1.92292928, -2.23317545, -0.31943611],
       [-2.25941791,  0.56408551,  0.82416569,  0.51359571,  0.1128809 ]])

In [24]:
#randint

np.random.randint(1,100)

97

In [32]:
np.random.randint(1,100,20)

array([72, 80, 77, 13, 61, 92, 86,  4, 30, 56, 16, 19, 76, 72, 82, 18, 72,
       30, 71, 54])

In [33]:
np.random.randint(1,100,(4,5))

array([[72, 99, 39, 54, 98],
       [36, 23,  4, 77, 97],
       [15, 67, 94, 67,  5],
       [48, 58, 98, 13, 53]])

# Array Attributes and Methods

In [42]:
arr = np.arange(30)
ranar = np.random.randint(0,50,10)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
ranar

array([48, 19, 43, 15, 19, 21, 40, 42, 31,  0])

In [37]:
ranar.max()

48

In [38]:
ranar.min()

0

In [39]:
ranar.argmax()

0

In [40]:
ranar.argmin()

9

In [45]:
arr_res = arr.reshape(3,10)

In [46]:
arr_res

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [47]:
arr_res.shape

(3, 10)

str, float, int, bool, datetime 

In [49]:
ranar.dtype

dtype('int32')