# Part 1: Manual Feature Extraction

In [6]:
#Bag of words

with open(r"C:\Users\shrey\Desktop\MLPP_iHUB_IITR_Sept_2023\DATA\One.txt") as  txt1:
    #a = txt1.read()  (read entire text as a string)
    #a = txt1.readlines() (read each line as a list)
    print(txt1.read())

This is a story about dogs
our canine pets
Dogs are furry animals



In [7]:
#a

In [8]:
with open(r"C:\Users\shrey\Desktop\MLPP_iHUB_IITR_Sept_2023\DATA\Two.txt") as  txt2:
    #b = txt2.read()
    #b = txt2.readlines()
    print(txt2.read())

This story is about surfing
Catching waves is fun
Surfing is a popular water sport



In [9]:
#b

# Create a 'Bag of Words' (create a vocabulary)

In [14]:
#Read words separately 

with open(r"C:\Users\shrey\Desktop\MLPP_iHUB_IITR_Sept_2023\DATA\One.txt") as  txt1:
    words1 = txt1.read().lower().split() 

In [15]:
words1

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [17]:
len(words1)

13

In [16]:
unique_words1 = set(words1)
unique_words1

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [20]:
with open(r"C:\Users\shrey\Desktop\MLPP_iHUB_IITR_Sept_2023\DATA\Two.txt") as  txt2:
    words2 = txt2.read().lower().split()
    unique_words2 = set(words2)
    

In [21]:
unique_words2

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [22]:
#Unique Words across both the documents
all_unique = set()
all_unique.update(unique_words1)

In [23]:
all_unique

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [24]:
all_unique.update(unique_words2)
all_unique

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [25]:
vocab = dict()
i = 0

for x in all_unique:
    vocab[x] = i
    i = i+1

In [27]:
vocab

{'our': 0,
 'furry': 1,
 'surfing': 2,
 'water': 3,
 'story': 4,
 'is': 5,
 'this': 6,
 'fun': 7,
 'popular': 8,
 'are': 9,
 'catching': 10,
 'waves': 11,
 'canine': 12,
 'pets': 13,
 'sport': 14,
 'animals': 15,
 'dogs': 16,
 'a': 17,
 'about': 18}

## Frequency Count on Bag of Words 

In [30]:
freq1 = [0]*len(vocab)
freq2 = [0]*len(vocab)
all_freq = ['']*len(vocab)

In [31]:
all_freq

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [32]:
for x in vocab:
    word_i = vocab[x]
    all_freq[word_i] = x

In [33]:
all_freq

['our',
 'furry',
 'surfing',
 'water',
 'story',
 'is',
 'this',
 'fun',
 'popular',
 'are',
 'catching',
 'waves',
 'canine',
 'pets',
 'sport',
 'animals',
 'dogs',
 'a',
 'about']

## Add in counts per words for each txt file

In [34]:
with open(r"C:\Users\shrey\Desktop\MLPP_iHUB_IITR_Sept_2023\DATA\One.txt") as f:
    one_txt = f.read().lower().split()
    
for x in one_txt:
    word_i = vocab[x]
    freq1[word_i] += 1

In [35]:
freq1

[1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 2, 1, 1]

In [40]:
with open(r"C:\Users\shrey\Desktop\MLPP_iHUB_IITR_Sept_2023\DATA\Two.txt") as f:
    two_txt = f.read().lower().split()
    
for x in two_txt:
    word_j = vocab[x]
    freq2[word_j] += 1

In [41]:
freq2

[0, 0, 2, 1, 1, 3, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1]

In [43]:
import pandas as pd
pd.DataFrame(data=[freq1,freq2], columns=all_freq)

our  furry  surfing  water  story  is  this  fun  popular  are  catching  \
0    1      1        0      0      1   1     1    0        0    1         0   
1    0      0        2      1      1   3     1    1        1    0         1   

   waves  canine  pets  sport  animals  dogs  a  about  
0      0       1     1      0        1     2  1      1  
1      1       0     0      1        0     0  1      1

# Part2:  Feature Extraction using sklearn

In [44]:
txt = ['This is line',
      'This is another line',
      'Completely different line']

## CountVectorizer

In [45]:
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer, CountVectorizer

In [53]:
cv = CountVectorizer()

In [54]:
sp_mat = cv.fit_transform(txt)

In [55]:
sp_mat.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [56]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [57]:
cv1 = CountVectorizer(stop_words='english')

In [58]:
cv1.fit_transform(txt).todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [59]:
cv1.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

# Tfidf

In [60]:
tfidf_t = TfidfTransformer()

In [61]:
cv2 = CountVectorizer()

In [62]:
counts = cv2.fit_transform(txt)

In [63]:
counts

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [64]:
tfidf_t.fit_transform(counts).todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

# Using PipeLine

In [66]:
from sklearn.pipeline import Pipeline

p = Pipeline([('cv2',CountVectorizer()),('tfidf',TfidfTransformer())])

In [67]:
results = p.fit_transform(txt)

In [68]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

 # tfidf Vectorizer (does above two in single step)

In [70]:
tfidf1 = TfidfVectorizer()

tfidf1.fit_transform(txt).todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])