# Import Libraries and Read Dataset

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\shrey\Desktop\MLPP_iHUB_IITR_Sept_2023\DATA\Advertising.csv")


In [3]:
X = df.drop('sales',axis=1)
y = df['sales']

# Polynomial Conversion

In [4]:
from sklearn.preprocessing import PolynomialFeatures

In [5]:
poly_conv = PolynomialFeatures(degree=3,include_bias=False)

In [6]:
poly_feat = poly_conv.fit_transform(X)

In [7]:
poly_feat

array([[2.30100000e+02, 3.78000000e+01, 6.92000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [4.45000000e+01, 3.93000000e+01, 4.51000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.72000000e+01, 4.59000000e+01, 6.93000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.77000000e+02, 9.30000000e+00, 6.40000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [2.83600000e+02, 4.20000000e+01, 6.62000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [2.32100000e+02, 8.60000000e+00, 8.70000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

# Train Test Split

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split( poly_feat, y, test_size=0.25, random_state=50)

# Scaling the Data

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
#help(StandardScaler)

In [12]:
scaler = StandardScaler()

In [13]:
#prevent data leakage 
scaler.fit(X_train)

StandardScaler()

In [14]:
sc_X_train = scaler.transform(X_train)
sc_X_test = scaler.transform(X_test)

# Ridge Regression

In [15]:
from sklearn.linear_model import Ridge

In [16]:
#help(Ridge)

In [17]:
r_model = Ridge(alpha=10)  #alpha is lambda in slides

In [18]:
r_model.fit(sc_X_train,y_train)

Ridge(alpha=10)

In [19]:
r_test_pred = r_model.predict(sc_X_test)
r_test_pred

array([13.43383402, 12.19340015,  9.04068673, 10.58059057, 10.68790931,
       18.04548137, 13.62233303,  6.73670706, 21.3210549 , 11.84381011,
       12.6381744 , 12.38553629, 22.56752819, 13.95672456, 12.91612286,
       16.92795723, 10.7525741 , 15.46366846,  9.40099008, 12.51852923,
       16.30346321, 10.43164934,  9.12720339, 12.32671384, 20.45474192,
       12.70116857,  8.90273379,  9.11577019, 14.96593896, 12.36127053,
       14.61259965, 10.48237499,  8.99033688, 15.93235379,  8.55925392,
        9.47629904, 12.71389753, 20.02382364,  9.9680283 , 11.12001289,
        8.60433278, 26.4947606 ,  9.51151394, 18.69350416, 15.95556515,
       10.30115496, 11.99653434, 12.5841494 ,  9.7914428 ,  8.02291771])

In [20]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
MAE = mean_absolute_error(y_test,r_test_pred)
MSE = mean_squared_error(y_test,r_test_pred)
RMSE = np.sqrt(MSE)

In [21]:
MAE

0.5045441562327649

In [22]:
MSE

0.3792640970052009

In [23]:
RMSE

0.6158442148832779

In [24]:
r_train_pred = r_model.predict(sc_X_train)
MAE_train = mean_absolute_error(y_train,r_train_pred)
MSE_train = mean_squared_error(y_train,r_train_pred)
RMSE_train = np.sqrt(MSE_train)

# Choose Alpha value with CV

In [25]:
from sklearn.linear_model import RidgeCV

In [26]:
#help(RidgeCV)

In [27]:
rcv_model = RidgeCV(alphas=(0.1,0.05, 1.0,10.0,25.0,95.0))

In [28]:
rcv_model.fit(sc_X_train,y_train)

RidgeCV(alphas=(0.1, 0.05, 1.0, 10.0, 25.0, 95.0))

In [29]:
rcv_model.alpha_

0.05

In [30]:
rcv_test_pred = rcv_model.predict(sc_X_test)
rcv_test_pred

array([13.94003916, 12.006844  ,  8.52357303, 10.91326951, 11.36051354,
       18.10179019, 13.24110347,  5.14919245, 21.32997085, 12.39054541,
       12.17955358, 12.54305934, 22.6379234 , 14.44265451, 12.28258009,
       17.84887017, 11.16060152, 15.49630512,  9.27521897, 13.27591855,
       17.36204142, 11.04954941,  9.43923143, 11.66134119, 20.45911633,
       13.34095974,  9.08627483,  9.31755801, 15.46706364, 11.9799298 ,
       15.76094127, 10.39962235,  8.57551053, 16.41380063,  8.6912475 ,
        9.40756967, 13.75834868, 20.05432816, 10.5665728 , 11.81334242,
        8.64947967, 25.80694861,  9.46980379, 19.33007937, 16.2569307 ,
        9.7375334 , 12.09600989, 12.31111434, 10.30180848,  7.22654874])

In [31]:
MAE_rcv = mean_absolute_error(y_test,rcv_test_pred)
MSE_rcv = mean_squared_error(y_test,rcv_test_pred)
RMSE_rcv = np.sqrt(MSE_rcv)

In [32]:
MAE_rcv

0.3115278466796113

In [33]:
MSE_rcv

0.14611040638569728

In [34]:
RMSE_rcv

0.3822439095468982

In [35]:
rcv_model.coef_

array([ 6.61938271,  0.43511619,  0.39844479, -8.77932248,  5.02116758,
       -0.73955236, -0.60177909, -0.01193372, -0.27523155,  4.02408433,
       -1.18150952,  0.54956121,  0.30734618, -0.4690718 ,  0.24244967,
        0.24357874,  0.24505987,  0.1379072 , -0.05711765])

# LASSO Regression

Least Absolute Shrinkage and Selection Operator

In [36]:
from sklearn.linear_model import LassoCV

In [44]:
lcv_model = LassoCV(eps=0.1, n_alphas=100, cv=6, max_iter=50000)  #eps is mean alpha to max alpha 

In [45]:
lcv_model.fit(sc_X_train,y_train)

LassoCV(cv=6, eps=0.1, max_iter=50000)

In [46]:
lcv_model.alpha_

0.5278831021815013

In [40]:
lcv_test_pred = lcv_model.predict(sc_X_test)
lcv_test_pred

array([13.44685445, 11.99578759,  9.40416787, 10.61287169, 10.98377035,
       17.81190718, 13.33915158,  8.27768248, 20.84875459, 11.83345135,
       12.27503202, 12.24907217, 21.76488932, 13.8839681 , 12.49173466,
       16.29948422, 10.82724719, 15.42509908,  9.96316659, 12.57289066,
       15.53568065, 10.84247226,  9.82794969, 11.79731885, 20.63477902,
       12.49210094,  9.31114332,  9.49985706, 14.91050859, 11.96790528,
       14.5687532 , 10.24610216,  9.2069109 , 15.89558169,  9.17499658,
       10.0297513 , 12.9166494 , 20.1028963 , 10.41889667, 11.4419987 ,
        9.43927328, 25.91472133, 10.00688722, 18.08313911, 15.85566964,
       10.50339602, 11.79908276, 12.34742492, 10.21781327,  8.85195091])

In [41]:
MAE_lcv = mean_absolute_error(y_test,lcv_test_pred)
MSE_lcv = mean_squared_error(y_test,lcv_test_pred)
RMSE_lcv = np.sqrt(MSE_lcv)

In [42]:
RMSE_lcv

0.7746408191393096

In [43]:
lcv_model.coef_

array([1.09542675, 0.        , 0.        , 0.        , 3.99185976,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

# Elastic Net

In [47]:
from sklearn.linear_model import ElasticNetCV

In [52]:
elastic_net_m = ElasticNetCV(l1_ratio=[.1,0.5,.95,.99,1], eps=0.01,n_alphas=100,max_iter=1000, random_state=50)

In [53]:
elastic_net_m.fit(sc_X_train,y_train)

ElasticNetCV(eps=0.01, l1_ratio=[0.1, 0.5, 0.95, 0.99, 1], random_state=50)

In [54]:
elastic_net_m.alpha_

0.052788310218150135

In [55]:
lcv_model.alpha_ #disregarding Ridge completely

0.5278831021815013

In [56]:
en_test_pred = elastic_net_m.predict(sc_X_test)
en_test_pred

array([13.85749989, 12.14032268,  8.60971741, 10.64772164, 10.76027567,
       18.38394966, 13.59585324,  6.61049895, 21.54820846, 11.72597931,
       12.42026525, 12.6111301 , 22.67640443, 14.31895992, 12.39581896,
       17.04769361, 10.8058904 , 15.77085496,  9.15017098, 12.76682386,
       16.29318892, 10.42155423,  9.11457189, 12.07334895, 20.65393132,
       12.55106452,  8.86786466,  9.135235  , 15.4070471 , 12.30645903,
       14.92627032, 10.40906596,  8.71009326, 16.42083367,  8.54850625,
        9.24104996, 12.95943961, 20.2516066 , 10.04295591, 11.1288087 ,
        8.53125595, 26.08799766,  9.23309234, 18.94178916, 16.3717028 ,
        9.92025565, 12.11791956, 12.19197606,  9.92868784,  7.62255909])

In [57]:
MAE_en = mean_absolute_error(y_test,en_test_pred)
MSE_en = mean_squared_error(y_test,en_test_pred)
RMSE_en = np.sqrt(MSE_en)

In [58]:
MAE_en

0.43735807218982203

In [59]:
MSE_en

0.32103004734877577

In [60]:
RMSE_en

0.5665951353027802